title: Walking Trail Properties
email: admin@walkingtrailproperties.com
description: >- # this means to ignore newlines until "baseurl:"
  Walking Trail Properties
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://walkingtrailproperties.com" # the base hostname & protocol for your site, e.g. http://example.com
future: true
# twitter_username: jekyllrb
github_username:  walkingtrailproperties
repository: "walkingtrailproperties/walkingtrailproperties.github.io"

# --
# man page
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/
# --
remote_theme : "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
locale: "en-US"
masthead_title: "Walking Trail Properties"
breadcrumbs: false
search: false
timezone: America/Los_Angeles
subtitle: "San Diego CA Rental Properties"
logo: "/assets/images/300x186.png"

head_scripts:
  - https://www.googletagmanager.com/gtag/js?id=G-GGBTBJ60NH
  - /assets/js/google-analytics.js

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: ["_pages"]

atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Build settings
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-sitemap  
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-archives
